/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplomenu;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author marcelo
 */
public class TelaLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 100, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Usuário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 100, 30);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 130, 100, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 50, 150, 30);

        jButton2.setText("Cancelar");
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 130, 100, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(140, 90, 150, 30);

        jButton3.setText("Testa Conexão");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(313, 13, 120, 30);

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 180, 100, 30);

        setBounds(0, 0, 475, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //para logar o usuário deve digitar 
        //usuario = aluno
        //senha = 123
        String usuario="aluno";
        String senha="123";
        String usuarioDigitado;
        String senhaDigitada;
        usuarioDigitado=jTextField1.getText();
        senhaDigitada=new String(jPasswordField1.getPassword());
        if( (usuario.equals(usuarioDigitado)) && (senha.equals(senhaDigitada))){
            this.dispose();
            NewJFrame.jMenuBar1.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Senha incorreta");
        }
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Conexao c;
        c = new Conexao();
        c.conecta();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Conexao c;
        c = new Conexao();
        Connection conn = c.conecta();
        String consulta;
        String usuario;
        String senha;
        usuario = jTextField1.getText();
        senha=new String(jPasswordField1.getPassword());
         
        consulta = "SELECT * FROM logar WHERE "
                + "login='"+usuario+"' AND "
                + "senha='"+senha+"';";
        System.out.println("Consulta "+consulta);
        
        Statement stmt;
        try {
            stmt = conn.createStatement();
            ResultSet resultado;
            resultado = stmt.executeQuery(consulta);
            while(resultado.next()){
                System.out.println(resultado.getString("nome"));
                this.dispose();
                NewJFrame.jMenuBar1.setVisible(true);
                NewJFrame.jLabel1.setText(resultado.getString("nome"));
            }
            
        } catch (Exception e) {
            System.out.println("Erro "+e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
